name: Check new release
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  check-new-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1.0.0
      - name: Check update
        run: |
          deno upgrade
          echo current_version=`npm view @kt3k/deno-bin-test-1 version` >> $GITHUB_ENV
          echo latest_version=`deno -V | awk '{print $2}'` >> $GITHUB_ENV
      - name: Debug
        run: |
          echo {{ env.latest_version }}
          echo {{ env.current_version }}
      - name: Bump
        if: env.latest_version != env.current_version
        run: |
          npm version {{ env.latest_version }}
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > $HOME/.npmrc
          npm publish
      - name: Push changes
        if: env.latest_version != env.current_version
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
